/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Letter = IDL.Record({
  'content' : IDL.Text,
  'fromPlayer' : IDL.Bool,
  'response' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});
export const LibraryCustomization = IDL.Record({
  'description' : IDL.Text,
  'itemName' : IDL.Text,
  'location' : IDL.Text,
});
export const GameState = IDL.Record({
  'letters' : IDL.Vec(Letter),
  'currentDialogueNode' : IDL.Opt(IDL.Nat),
  'trustLevel' : IDL.Int,
  'endingsUnlocked' : IDL.Vec(IDL.Text),
  'unlockedMoments' : IDL.Vec(IDL.Text),
  'completedActivities' : IDL.Vec(IDL.Text),
  'libraryCustomizations' : IDL.Vec(LibraryCustomization),
});

export const idlService = IDL.Service({
  'completeActivity' : IDL.Func([IDL.Text], [], []),
  'continueGame' : IDL.Func([], [GameState], []),
  'getGameState' : IDL.Func([], [GameState], []),
  'isAvailable' : IDL.Func([], [IDL.Bool], ['query']),
  'makeChoice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'placeCustomization' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'resetProgress' : IDL.Func([], [], []),
  'respondToLetter' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'startNewGame' : IDL.Func([], [], []),
  'unlockMoment' : IDL.Func([IDL.Text], [], []),
  'writeLetter' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Letter = IDL.Record({
    'content' : IDL.Text,
    'fromPlayer' : IDL.Bool,
    'response' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  const LibraryCustomization = IDL.Record({
    'description' : IDL.Text,
    'itemName' : IDL.Text,
    'location' : IDL.Text,
  });
  const GameState = IDL.Record({
    'letters' : IDL.Vec(Letter),
    'currentDialogueNode' : IDL.Opt(IDL.Nat),
    'trustLevel' : IDL.Int,
    'endingsUnlocked' : IDL.Vec(IDL.Text),
    'unlockedMoments' : IDL.Vec(IDL.Text),
    'completedActivities' : IDL.Vec(IDL.Text),
    'libraryCustomizations' : IDL.Vec(LibraryCustomization),
  });
  
  return IDL.Service({
    'completeActivity' : IDL.Func([IDL.Text], [], []),
    'continueGame' : IDL.Func([], [GameState], []),
    'getGameState' : IDL.Func([], [GameState], []),
    'isAvailable' : IDL.Func([], [IDL.Bool], ['query']),
    'makeChoice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'placeCustomization' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'resetProgress' : IDL.Func([], [], []),
    'respondToLetter' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'startNewGame' : IDL.Func([], [], []),
    'unlockMoment' : IDL.Func([IDL.Text], [], []),
    'writeLetter' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };