/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameState {
  'letters' : Array<Letter>,
  'currentDialogueNode' : [] | [bigint],
  'trustLevel' : bigint,
  'endingsUnlocked' : Array<string>,
  'unlockedMoments' : Array<string>,
  'transfurred' : boolean,
  'completedActivities' : Array<string>,
  'timesTransfurred' : bigint,
  'libraryCustomizations' : Array<LibraryCustomization>,
}
export interface Letter {
  'content' : string,
  'fromPlayer' : boolean,
  'response' : [] | [string],
  'timestamp' : Time,
}
export interface LibraryCustomization {
  'description' : string,
  'itemName' : string,
  'location' : string,
}
export type Time = bigint;
export interface UserProfile { 'gamesPlayed' : bigint, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeActivity' : ActorMethod<[string], undefined>,
  'continueGame' : ActorMethod<[], GameState>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameState' : ActorMethod<[], GameState>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAvailable' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeChoice' : ActorMethod<[bigint, bigint], undefined>,
  'placeCustomization' : ActorMethod<[string, string, string], undefined>,
  'recordTransfurred' : ActorMethod<[], undefined>,
  'resetProgress' : ActorMethod<[], undefined>,
  'respondToLetter' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startNewGame' : ActorMethod<[], undefined>,
  'unlockMoment' : ActorMethod<[string], undefined>,
  'writeLetter' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];