/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LibraryCustomization {
    description: string;
    itemName: string;
    location: string;
}
export interface Letter {
    content: string;
    fromPlayer: boolean;
    response?: string;
    timestamp: Time;
}
export type Time = bigint;
export interface GameState {
    letters: Array<Letter>;
    currentDialogueNode?: bigint;
    trustLevel: bigint;
    endingsUnlocked: Array<string>;
    unlockedMoments: Array<string>;
    completedActivities: Array<string>;
    libraryCustomizations: Array<LibraryCustomization>;
}
export interface backendInterface {
    completeActivity(activityName: string): Promise<void>;
    continueGame(): Promise<GameState>;
    getGameState(): Promise<GameState>;
    makeChoice(nodeId: bigint, choiceId: bigint): Promise<void>;
    placeCustomization(itemName: string, description: string, location: string): Promise<void>;
    resetProgress(): Promise<void>;
    respondToLetter(letterIndex: bigint, response: string): Promise<void>;
    startNewGame(): Promise<void>;
    unlockMoment(momentTitle: string): Promise<void>;
    writeLetter(content: string): Promise<void>;
}
import type { GameState as _GameState, Letter as _Letter, LibraryCustomization as _LibraryCustomization, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeActivity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeActivity(arg0);
            return result;
        }
    }
    async continueGame(): Promise<GameState> {
        if (this.processError) {
            try {
                const result = await this.actor.continueGame();
                return from_candid_GameState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.continueGame();
            return from_candid_GameState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameState(): Promise<GameState> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameState();
                return from_candid_GameState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameState();
            return from_candid_GameState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async makeChoice(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.makeChoice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeChoice(arg0, arg1);
            return result;
        }
    }
    async placeCustomization(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeCustomization(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeCustomization(arg0, arg1, arg2);
            return result;
        }
    }
    async resetProgress(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetProgress();
            return result;
        }
    }
    async respondToLetter(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToLetter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToLetter(arg0, arg1);
            return result;
        }
    }
    async startNewGame(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startNewGame();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startNewGame();
            return result;
        }
    }
    async unlockMoment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockMoment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockMoment(arg0);
            return result;
        }
    }
    async writeLetter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.writeLetter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.writeLetter(arg0);
            return result;
        }
    }
}
function from_candid_GameState_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameState): GameState {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Letter_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Letter): Letter {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    letters: Array<_Letter>;
    currentDialogueNode: [] | [bigint];
    trustLevel: bigint;
    endingsUnlocked: Array<string>;
    unlockedMoments: Array<string>;
    completedActivities: Array<string>;
    libraryCustomizations: Array<_LibraryCustomization>;
}): {
    letters: Array<Letter>;
    currentDialogueNode?: bigint;
    trustLevel: bigint;
    endingsUnlocked: Array<string>;
    unlockedMoments: Array<string>;
    completedActivities: Array<string>;
    libraryCustomizations: Array<LibraryCustomization>;
} {
    return {
        letters: from_candid_vec_n3(_uploadFile, _downloadFile, value.letters),
        currentDialogueNode: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.currentDialogueNode)),
        trustLevel: value.trustLevel,
        endingsUnlocked: value.endingsUnlocked,
        unlockedMoments: value.unlockedMoments,
        completedActivities: value.completedActivities,
        libraryCustomizations: value.libraryCustomizations
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    fromPlayer: boolean;
    response: [] | [string];
    timestamp: _Time;
}): {
    content: string;
    fromPlayer: boolean;
    response?: string;
    timestamp: Time;
} {
    return {
        content: value.content,
        fromPlayer: value.fromPlayer,
        response: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.response)),
        timestamp: value.timestamp
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Letter>): Array<Letter> {
    return value.map((x)=>from_candid_Letter_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
